-- 店舗に緯度・経度・GPS許容半径を追加
ALTER TABLE store ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE store ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE store ADD COLUMN IF NOT EXISTS gps_radius_meters INTEGER DEFAULT 50;
